# Generated by Django 2.1.1 on 2020-07-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMMachineLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16)),
                ('name', models.CharField(default='', max_length=255)),
                ('keep', models.PositiveSmallIntegerField(default='1')),
                ('rank', models.PositiveSmallIntegerField(default='0')),
                ('recommendation', models.PositiveSmallIntegerField(default='0')),
                ('accuracy', models.FloatField(default='0')),
                ('auc', models.FloatField(default='0')),
                ('logloss', models.FloatField(default='0')),
                ('mean_per_class_error', models.FloatField(default='0')),
                ('rmse', models.FloatField(default='0')),
                ('mse', models.FloatField(default='0')),
                ('modelfile', models.FileField(blank=True, null=True, upload_to='static/file/')),
                ('summary', models.TextField(default='')),
                ('parameter', models.TextField(default='')),
                ('fullParameter', models.TextField(default='')),
                ('mcc', models.FloatField(default='0')),
                ('f1score', models.FloatField(default='0')),
                ('numberCV', models.PositiveSmallIntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='PMMLCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('modelfile', models.FileField(blank=True, null=True, upload_to='static/file/')),
                ('ml', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='core.PMMachineLearning')),
            ],
        ),
        migrations.CreateModel(
            name='PMMLPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=255)),
                ('confidence', models.FloatField(default='0')),
                ('ml', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.PMMachineLearning')),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('uid', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(default='', max_length=255)),
                ('task', models.CharField(default='', max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/file/')),
                ('nModel', models.PositiveSmallIntegerField(default='3')),
                ('maxRuntime', models.PositiveIntegerField(default='600')),
                ('runAdvanced', models.PositiveIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveModelFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
                ('type', models.CharField(default='categorical', max_length=32)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.PredictiveModel')),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveModelSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=255)),
                ('type', models.CharField(default='train', max_length=32)),
                ('target', models.CharField(default=' ', max_length=32)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.PredictiveModel')),
            ],
        ),
        migrations.AddField(
            model_name='pmmlprediction',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_predictions', to='core.PredictiveModelSample'),
        ),
        migrations.AddField(
            model_name='pmmachinelearning',
            name='core',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_sample', to='core.PredictiveModelSample'),
        ),
    ]
