# Generated by Django 2.1.1 on 2020-07-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmmachinelearning',
            name='core',
        ),
        migrations.RemoveField(
            model_name='predictivemodel',
            name='runAdvanced',
        ),
        migrations.AlterField(
            model_name='predictivemodel',
            name='maxRuntime',
            field=models.PositiveIntegerField(default='60'),
        ),
        migrations.AlterField(
            model_name='predictivemodel',
            name='nModel',
            field=models.PositiveSmallIntegerField(default='1'),
        ),
    ]
